### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by KamasamaK** [Ortus-Solutions/vscode-commandbox#1]
Related to KamasamaK/vscode-cfml#42 and KamasamaK/vscode-cfml#46

Since I haven't received write access to this repository yet, I have made one under my own user for now -- [KamasamaK/vscode-commandbox](https://github.com/KamasamaK/vscode-commandbox/tree/master). I am not really a CommandBox poweruser, so please test this release and let me know what issues you find. For now, the functionality is pretty basic and roughly equivalent to what is available in the NPM extension. To test, you can install the [release VSIX binary](https://github.com/KamasamaK/vscode-commandbox/releases) from 
Extensions view -> ... -> Install from VSIX...

cc @lmajano

**Comment by lmajano** [comment]
Ok, access granted

**Comment by lmajano** [comment]
This is great!!

**Comment by KamasamaK** [comment]
Since there's been no feedback, I've decided to just commit the v1.0 here and @lmajano can publish when ready. I am having an issue writing to the repository, though. I am getting
```
remote: Permission to Ortus-Solutions/vscode-commandbox.git denied to KamasamaK.
fatal: unable to access 'https://github.com/Ortus-Solutions/vscode-commandbox.git/': The requested URL returned error: 403
```

**Comment by bdw429s** [comment]
@KamasamaK Sorry, I think this fell under the radar here.  I don't appear to be an admin on this repo so I can't review or fix your permissions. :disappointed:  I've pinged @lmajano to help out or fix my permissions so I can fix yours :smile: 

Once we get the permissions straightened out, I think it would be great to do a quick call and have you demo it to the team so we can get a feel for it.

**Comment by lmajano** [comment]
Weird, I have tweaked it a bit, but you should be good though as per the settings

**Comment by KamasamaK** [comment]
Hmm. Still getting the same error. And I can't fork + PR because GitHub doesn't allow forking an empty repository.

**Comment by bdw429s** [comment]
@KamasamaK According to the settings, you have not accepted your invite.  Please try this URL to see if you can accept it

https://github.com/Ortus-Solutions/vscode-commandbox/invitations

**Comment by KamasamaK** [comment]
@bdw429s Thanks. That was probably it, but when I clicked on Accept it said that the invitation was expired. I never actually got a notification of the invitation and aside from your direct link I'm not sure how I would have ever found it.

**Comment by bdw429s** [comment]
@KamasamaK I sent a fresh invitation just now.  Please see if you can accept it.

https://github.com/Ortus-Solutions/vscode-commandbox/invitations

**Comment by KamasamaK** [comment]
Done

**Comment by bdw429s** [comment]
@KamasamaK @lmajano When can we do a quick call to go over the features?

**Comment by KamasamaK** [comment]
@bdw429s It's pretty simple at the moment. It's really just an adaptation of the `npm` extension. I tried to document all the features in the README with images, but if you want a quick call I can probably make time whenever you guys want. I am in EDT so not too different from you.

**Comment by bdw429s** [comment]
@KamasamaK Can you help explain this to me?

> This extension supports running CommandBox scripts as tasks. Scripts containing the name 'build', 'compile', or 'watch' are treated as build tasks. Any scripts defined in the box.json will be auto-detected by default and added as tasks. You can also annotate task definitions in your tasks.json files using the type as commandbox and script as the script name.

What does it mean running scripts as tasks? Like a Task Runner or is this something else related to VSCode?
What is a "build task" and what does it mean to treat a script like one?
What is the `task.json` file?

**Comment by michaelborn** [comment]
@bdw429s Yep, "tasks" is a VS Code feature which puts all npm package scripts as executable entries in a sidebar pane, as well as making them accessible from a "Command Palette" menu.

* User-friendly overview: https://vscode.rocks/tasks/
* Dev-friendly overview: https://code.visualstudio.com/Docs/editor/tasks

**Comment by bdw429s** [comment]
Ahh, I see.  I'm not sure how I feel about calling "package scripts" as "tasks" when the word task already has another meaning in CommandBox.  Can we change the name in our extension, or are "tasks" a core feature and we're stuck with the name.

On that note, it would be nice to be able to introspect your project for `task.cfc` task runners and run them.  Not sure how you'd handle input though.

I'm still curious about the difference of a "build" task (compared to non-build tasks).

**Comment by KamasamaK** [comment]
"Tasks" are the name of the feature in VS Code and the extension registers the scripts as VS Code tasks using a [Task Provider](https://code.visualstudio.com/api/extension-guides/task-provider). @michaelborn  provided some good overviews. The "Terminal" menu in VS Code actually has options to run or configure tasks. There are also Tasks commands native to VS Code.

I don't use VS Code tasks extensively so I may not be the best person to ask about use cases. I don't know offhand what all the implications are for annotating a task as "build" or "test" kind aside from grouping in the UI. The only use I've had for tasks aside from executing them directly is referencing in a [launch configuration](https://code.visualstudio.com/docs/editor/debugging#_launch-configurations).

Again, this is just adapted to how the `npm` extension implements these features in VS Code.

I'm not too familiar with `task.cfc`, but it should be possible to do what you want.

**Comment by KamasamaK** [comment]
I've clarified the use of VS Code tasks in the documentation.

**Comment by bdw429s** [comment]
Cool, thx.  I think this is all making good sense now. I'd say the two things we can look into for a "next step" in regards to those tasks would be

Finding and auto-running recipes in a project
https://commandbox.ortusbooks.com/usage/execution/recipes

Finding and auto-running Task Runners
https://commandbox.ortusbooks.com/task-runners

The only wrinkle being that both of those can accept user arguments when run, even though that's optional.

**Comment by KamasamaK** [comment]
At this point, it's just up to @lmajano to publish to the VS Code Marketplace.

**Comment by bdw429s** [comment]
@lmajano What's the status getting this published to the VS Code Marketplace?

**Comment by lmajano** [comment]
Sorry guys, I have been knee deep in ColdBox 6. I am reading all the comments and trying this out. What I would love to do is add @KamasamaK to our vs code portal so he can do releases as well.

**Comment by lmajano** [comment]
@KamasamaK can I bother you with a section on the readme on how to collaborate on the extension.  This will be helpful to get our devs to build and test out the extension as well.

**Comment by lmajano** [comment]
@KamasamaK can we do a video call with our team so we can get an overview and some knowledge transfer so we can start helping and hacking on the extension? I would love to pay for your time.

**Comment by lmajano** [comment]
By the way, I published the current version

**Comment by lmajano** [comment]
![image](https://user-images.githubusercontent.com/137111/78915283-4bbf7680-7a51-11ea-85fc-2a1a8ba45b20.png)

**Comment by KamasamaK** [comment]
@lmajano For me to be able to publish, you will need to create a Personal Access Token for me in your organization. We can discuss that and a call in Slack.

I will look at creating a CONTRIBUTING.md to explain how to contribute.

**Comment by lmajano** [comment]
Thanks @KamasamaK I have our SV (El Salvador) team, eager to start helping out and learning
