### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by KamasamaK** [Ortus-Solutions/vscode-commandbox#18]
Apparently, Microsoft prohibits the usage of the Visual Studio Marketplace by any other non-Microsoft products. Because of this, I would recommend taking ownership of your namespace in [OpenVSX](https://open-vsx.org/) and publish there as well.

OpenVSX is a vendor-neutral alternative to the Visual Studio Marketplace used by all other derivatives of VS Code like Gitpod, OpenVSCode, VSCodium, Theia-based IDEs, etc.

Before publishing, you will need to complete Steps 1-4 in [these instructions](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

For publishing, I will be streamlining this process by adding a GitHub Actions release workflow that creates the GitHub release and publishes to both the Visual Studio Marketplace and OpenVSX. The publishing will use your access tokens that you set in GitHub Repository Secrets. For the Visual Studio Marketplace token, name the secret `VSCE_PAT` -- ensure the token is still valid since they expire yearly. For the OpenVSX token, name the secret `OVSX_PAT`.

Please let me know when all of that is done or if you're not interested in publishing to OpenVSX.

This also essentially addresses https://github.com/Ortus-Solutions/vscode-commandbox/issues/1#issuecomment-611586991 without needing to give me direct access to publishing for your organization.

**Comment by jclausen** [comment]
@KamasamaK : I am assuming you are referring to this clause in the [terms and conditions](https://marketplace.visualstudio.com/items/ms-vscode.cpptools/license):

> You may install and use any number of copies of the software only with Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Azure DevOps, Team Foundation Server, and successor Microsoft products and services to develop and test your applications.

If so, my suggestion would be to go the dual-publish route using your action, when it is available.  Please feel free to submit a PR once your action is added and we can evaluate.

**Comment by lmajano** [comment]
Thanks @KamasamaK I have it on my todo list now.

**Comment by KamasamaK** [comment]
@lmajano It's been about two months since you last commented, so I was wondering if you were able to get to this yet. I basically have v1.1.0 ready to go.

**Comment by lmajano** [comment]
Sorry @KamasamaK things have been wild.  I have not forgotten, but it has taken me more than I thought.

**Comment by lmajano** [comment]
@bdw429s can you assist me in getting the credentials please

**Comment by lmajano** [comment]
Ok, I am creating the accounts. WOW, such a convoluted process in eclipse.  IT did not allow me to use the ortus account. So I had to do it with mine.

**Comment by lmajano** [comment]
Ok, done, we are ready to roll, what do you need me to do

**Comment by KamasamaK** [comment]
@lmajano You don't need to do anything else right now. The only thing pending is the approval of your namespace ownership.

The release workflow was successful
https://github.com/Ortus-Solutions/vscode-commandbox/actions/runs/2637928469

VS Marketplace extension was updated
https://marketplace.visualstudio.com/items?itemName=ortus-solutions.vscode-commandbox

Open VSX extension was published
https://open-vsx.org/extension/ortus-solutions/vscode-commandbox

**Comment by lmajano** [comment]
Great thanks so much @KamasamaK and my apologies for such a long delay.
