### ISSUE TITLE
server.schema.json JVM args type

### ISSUE THREAD

**Issue by chapmandu** [Ortus-Solutions/vscode-commandbox#25]
server.schema.json specifies the type as string.
```
"args": {
	"title": "JVM Arguments",
	"description": "Ad-hoc JVM args for the server such as -X:name",
	"type": "string",
	"default": ""
}
```
https://commandbox.ortusbooks.com/embedded-server/configuring-your-server/jvm-args indicates an array of strings.

When using the the config below in `server.json`, the schema validator indicates a problem.

![image](https://user-images.githubusercontent.com/1092563/182269048-1d68611a-9484-486d-be52-fae43822f5d1.png)

Thanks for this great extension.

**Comment by bdw429s** [comment]
@chapmandu The JSON Schema file that controls that is here:
https://github.com/Ortus-Solutions/commandbox/blob/development/src/cfml/system/config/server.schema.json
Do you want to try and make the changes that are necessary?

**Comment by chapmandu** [comment]
PR created https://github.com/Ortus-Solutions/commandbox/pull/312

**Comment by KamasamaK** [comment]
@bdw429s It actually gets pulled from the `Ortus-Solutions/commandbox` repo every time the extension starts if you have internet connectivity, but I will always commit the latest one before a new release to fall back on.
