### ISSUE TITLE
Verify Publisher on VS Marketplace

### ISSUE THREAD

**Issue by KamasamaK** [Ortus-Solutions/vscode-commandbox#29]
Not specific to this extension, but `ortus-solutions` is a verified publisher on Open VSX, but not on the Visual Studio Marketplace. If you'd like to verify the publisher there as well, follow the instructions [here](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher).

**Comment by bdw429s** [comment]
@KamasamaK Is something @lmajano needs to do?

**Comment by KamasamaK** [comment]
Yes. It requires someone with access to the Visual Studio Marketplace publisher management as well as someone with access to the DNS configuration for ortussolutions.com.

**Comment by lmajano** [comment]
Added to my todo list



Luis Majano
CEO
Ortus Solutions, Corp
1-888-557-8057
909-248-3408
www.ortussolutions.com
Support Open Source: www.patreon.com/ortussolutions
Linked In: https://www.linkedin.com/pub/3/731/483
Social: twitter.com/ortussolutions | twitter.com/lmajano

**Comment by lmajano** [comment]
Done
